"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](fg:bg_left)\
[ ](bg:bg_left)\
$os\
$username\
[](bg:bg_center fg:bg_left)\
$directory\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$kotlin\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](bg:bg_center fg:bg_right)\
$git_branch\
$git_status\
$docker_context\
[ ](bg:bg_right)\
[ ](fg:bg_right)\
"""

palette = 'splatoon1'

[palettes.splatoon1]
bg_left = '#de6624'
bg_center = '#404040'
bg_right = '#343bc4'
fg_left = '#000000'
fg_center = '#ffffff'
fg_center_s = '#a0a0a0'
fg_right = '#ffffff'
fg_right_s = '#a0a0a0'

[palettes.splatoon2]
bg_left = '#c12d74'
bg_center = '#404040'
bg_right = '#2cb721'
fg_left = '#000000'
fg_center = '#ffffff'
fg_center_s = '#a0a0a0'
fg_right = '#000000'
fg_right_s = '#404040'

[palettes.splatoon3]
bg_left = '#d0bf08'
bg_center = '#404040'
bg_right = '#3a0ccd'
fg_left = '#000000'
fg_center = '#ffffff'
fg_center_s = '#a0a0a0'
fg_right = '#ffffff'
fg_right_s = '#a0a0a0'

[username]
show_always = true
style_user = "bg:bg_left fg:fg_left"
style_root = "bg:bg_left fg:fg_left"
format = '[ $user ]($style)'
disabled = false

[os]
disabled = false
style = "bg:bg_left fg:fg_left"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "bg:bg_center fg:fg_center"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "
"dev" = "󰲋 "

[c]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:bg_center fg:fg_center_s"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:bg_center fg:fg_center_s"
format = '[ ♥ $time ]($style)'

[git_branch]
symbol = ""
style = "bg:bg_right fg:fg_right"
format = '[  $symbol $branch ]($style)'

[git_status]
style = "bg:bg_right fg:fg_right"
format = '[$all_status$ahead_behind ]($style)'

[docker_context]
symbol = " "
style = "bg:bg_right fg:fg_right_s"
format = '[$symbol $context ]($style)'
