format = """
[](#d0bf08)\
$os\
$username\
[\uE0B8](bg:#404040 fg:#d0bf08)\
$directory\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[\uE0B8](fg:#404040 bg:#3a0ccd)\
$git_branch\
$git_status\
$docker_context\
[\uE0B8 ](fg:#3a0ccd)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#d0bf08 fg:#202020"
style_root = "bg:#d0bf08 fg:#202020"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E fg:#202020"
disabled = true                 # Disabled by default

[directory]
style = "bg:#404040 fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#3a0ccd"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3a0ccd"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#404040"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
